"""add_workshop_invite_contacts_table

Revision ID: 3cf357a1e098
Revises: dd331deedd6d
Create Date: 2026-03-27 07:32:19.138041

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3cf357a1e098'
down_revision = 'dd331deedd6d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workshop_invite_contacts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workshop_id', sa.Integer(), nullable=False),
    sa.Column('crm_contact_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('email_type', sa.String(length=30), nullable=True),
    sa.ForeignKeyConstraint(['workshop_id'], ['workshops.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workshop_id', 'crm_contact_id', 'email_type', name='uq_workshop_contact_type')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('workshop_invite_contacts')
    # ### end Alembic commands ###
