"""Add shadow tables for resilience

Revision ID: 3fc4ca39dfe7
Revises: 436baaa28d93
Create Date: 2026-03-12 06:38:56.941974

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3fc4ca39dfe7'
down_revision = '436baaa28d93'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shadow_clients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('crm_client_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=True),
    sa.Column('logo', sa.String(length=500), nullable=True),
    sa.Column('last_synced', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('crm_client_id')
    )
    op.create_table('shadow_contacts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('crm_contact_id', sa.Integer(), nullable=False),
    sa.Column('crm_client_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('last_synced', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('crm_contact_id')
    )
    op.create_table('shadow_staff_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('crm_user_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('first_name', sa.String(length=100), nullable=True),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.Column('role', sa.String(length=50), nullable=True),
    sa.Column('last_synced', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('crm_user_id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('shadow_trainers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('crm_trainer_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('photo_url', sa.String(length=500), nullable=True),
    sa.Column('expertise', sa.Text(), nullable=True),
    sa.Column('last_synced', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('crm_trainer_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('shadow_trainers')
    op.drop_table('shadow_staff_users')
    op.drop_table('shadow_contacts')
    op.drop_table('shadow_clients')
    # ### end Alembic commands ###
