"""add otp_tokens table

Revision ID: 436baaa28d93
Revises: d646d1c04c74
Create Date: 2026-03-09 13:28:38.833271

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '436baaa28d93'
down_revision = 'd646d1c04c74'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('otp_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=30), nullable=False),
    sa.Column('code', sa.String(length=6), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('used', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('otp_tokens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_otp_tokens_email'), ['email'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('otp_tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_otp_tokens_email'))

    op.drop_table('otp_tokens')
    # ### end Alembic commands ###
