"""assessment_engine_mcq_scoring

Revision ID: bfe7c9524fb5
Revises: 2ea0bf9048ba
Create Date: 2026-05-13 04:32:33.348814

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bfe7c9524fb5'
down_revision = '2ea0bf9048ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assessment_questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('assessment_id', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('question_type', sa.String(length=30), nullable=True),
    sa.Column('points', sa.Integer(), nullable=True),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['assessment_id'], ['program_assessments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('question_options',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(length=512), nullable=False),
    sa.Column('is_correct', sa.Boolean(), nullable=True),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['assessment_questions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('quiz_responses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('assignment_id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('selected_option_id', sa.Integer(), nullable=True),
    sa.Column('text_answer', sa.Text(), nullable=True),
    sa.Column('is_correct', sa.Boolean(), nullable=True),
    sa.Column('points_awarded', sa.Float(), nullable=True),
    sa.Column('answered_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['assignment_id'], ['assessment_assignments.id'], ),
    sa.ForeignKeyConstraint(['question_id'], ['assessment_questions.id'], ),
    sa.ForeignKeyConstraint(['selected_option_id'], ['question_options.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('assessment_assignments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('attempts', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('score', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('max_score', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('raw_points', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('graded_by', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('graded_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('feedback', sa.Text(), nullable=True))

    with op.batch_alter_table('certificates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('program_title', sa.String(length=255), nullable=True))
        batch_op.alter_column('workshop_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('registration_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('program_assessments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('pass_score', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('time_limit_minutes', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('max_attempts', sa.Integer(), nullable=True))
        batch_op.alter_column('file_url',
               existing_type=sa.VARCHAR(length=512),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('program_assessments', schema=None) as batch_op:
        batch_op.alter_column('file_url',
               existing_type=sa.VARCHAR(length=512),
               nullable=False)
        batch_op.drop_column('max_attempts')
        batch_op.drop_column('time_limit_minutes')
        batch_op.drop_column('pass_score')
        batch_op.drop_column('description')

    with op.batch_alter_table('certificates', schema=None) as batch_op:
        batch_op.alter_column('registration_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('workshop_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('program_title')

    with op.batch_alter_table('assessment_assignments', schema=None) as batch_op:
        batch_op.drop_column('feedback')
        batch_op.drop_column('graded_at')
        batch_op.drop_column('graded_by')
        batch_op.drop_column('raw_points')
        batch_op.drop_column('max_score')
        batch_op.drop_column('score')
        batch_op.drop_column('attempts')

    op.drop_table('quiz_responses')
    op.drop_table('question_options')
    op.drop_table('assessment_questions')
    # ### end Alembic commands ###
