"""Add Training Management enhancements

Revision ID: d7f6dd4d0d18
Revises: e58c844964c3
Create Date: 2026-03-19 07:30:16.216190

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd7f6dd4d0d18'
down_revision = 'e58c844964c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('program_assessments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('crm_engagement_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('file_url', sa.String(length=512), nullable=False),
    sa.Column('assessment_type', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('program_assessments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_program_assessments_crm_engagement_id'), ['crm_engagement_id'], unique=False)

    op.create_table('program_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('crm_engagement_id', sa.Integer(), nullable=False),
    sa.Column('assessments_enabled', sa.Boolean(), nullable=True),
    sa.Column('labs_enabled', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('program_configs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_program_configs_crm_engagement_id'), ['crm_engagement_id'], unique=True)

    op.create_table('program_labs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('crm_engagement_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('lab_url', sa.String(length=512), nullable=False),
    sa.Column('access_start', sa.DateTime(), nullable=True),
    sa.Column('access_end', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('program_labs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_program_labs_crm_engagement_id'), ['crm_engagement_id'], unique=False)

    op.create_table('program_participants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('crm_engagement_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('organization', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('program_participants', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_program_participants_crm_engagement_id'), ['crm_engagement_id'], unique=False)

    op.create_table('assessment_assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('assessment_id', sa.Integer(), nullable=False),
    sa.Column('participant_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('assigned_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['assessment_id'], ['program_assessments.id'], ),
    sa.ForeignKeyConstraint(['participant_id'], ['program_participants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lab_assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lab_id', sa.Integer(), nullable=False),
    sa.Column('participant_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('assigned_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['lab_id'], ['program_labs.id'], ),
    sa.ForeignKeyConstraint(['participant_id'], ['program_participants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('lab_assignments')
    op.drop_table('assessment_assignments')
    with op.batch_alter_table('program_participants', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_program_participants_crm_engagement_id'))

    op.drop_table('program_participants')
    with op.batch_alter_table('program_labs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_program_labs_crm_engagement_id'))

    op.drop_table('program_labs')
    with op.batch_alter_table('program_configs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_program_configs_crm_engagement_id'))

    op.drop_table('program_configs')
    with op.batch_alter_table('program_assessments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_program_assessments_crm_engagement_id'))

    op.drop_table('program_assessments')
    # ### end Alembic commands ###
