"""Add learner_id to program_participants

Revision ID: dd331deedd6d
Revises: d7f6dd4d0d18
Create Date: 2026-03-20 06:24:44.850139

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd331deedd6d'
down_revision = 'd7f6dd4d0d18'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('program_participants', schema=None) as batch_op:
        batch_op.add_column(sa.Column('learner_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_participant_learner', 'learners', ['learner_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('program_participants', schema=None) as batch_op:
        batch_op.drop_constraint('fk_participant_learner', type_='foreignkey')
        batch_op.drop_column('learner_id')

    # ### end Alembic commands ###
