"""Add managed program and activation flags

Revision ID: e58c844964c3
Revises: 3fc4ca39dfe7
Create Date: 2026-03-13 09:13:28.273599

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e58c844964c3'
down_revision = '3fc4ca39dfe7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workshop_activity_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workshop_id', sa.Integer(), nullable=False),
    sa.Column('learner_id', sa.Integer(), nullable=False),
    sa.Column('registration_id', sa.Integer(), nullable=False),
    sa.Column('activity_type', sa.String(length=50), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['learner_id'], ['learners.id'], ),
    sa.ForeignKeyConstraint(['registration_id'], ['workshop_registrations.id'], ),
    sa.ForeignKeyConstraint(['workshop_id'], ['workshops.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('learners', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('password_hash', sa.String(length=255), nullable=True))
        batch_op.create_unique_constraint('uq_learners_username', ['username'])

    with op.batch_alter_table('workshops', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_lms_managed', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('admin_ready', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('crm_engagement_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_workshops_crm_engagement_id'), ['crm_engagement_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workshops', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_workshops_crm_engagement_id'))
        batch_op.drop_column('crm_engagement_id')
        batch_op.drop_column('admin_ready')
        batch_op.drop_column('is_lms_managed')

    with op.batch_alter_table('learners', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('password_hash')
        batch_op.drop_column('username')

    op.drop_table('workshop_activity_logs')
    # ### end Alembic commands ###
